language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-dj21
    - python: 3.7
      env: TOXENV=py37-dj22
    - python: 3.7
      env: TOXENV=py37-dj30

install:
  - ./.travis/install

script:
  - ./.travis/run tox
